job_parser/job_parser/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("parser.urls")),
    path("profiles/", include("profiles.urls", namespace="profiles")),
    path("accounts/", include("allauth.urls")),
]


if settings.DEBUG:
    urlpatterns = [
        path("__debug__/", include("debug_toolbar.urls")),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job_parser/parser/urls.py
from django.urls import path

from .views.blacklist import (
    AddToBlackListView,
    ClearBlackList,
    DeleteFromBlacklistView,
)
from .views.favourite import (
    AddToFavouritesView,
    ClearFavouriteList,
    DeleteFromFavouritesView,
)
from .views.hiddenCompanies import (
    ClearHiddenCompaniesList,
    DeleteFromHiddenCompaniesView,
    HideCompanyView,
)
from .views.home import HomePageView
from .views.vacancies import VacancyListView

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("vacancies/", VacancyListView.as_view(), name="vacancies"),
    path("favourite/", AddToFavouritesView.as_view(), name="favourite"),
    path(
        "delete-favourite/",
        DeleteFromFavouritesView.as_view(),
        name="delete_favourite",
    ),
    path(
        "clear-favourite-list/",
        ClearFavouriteList.as_view(),
        name="clear_favourite_list",
    ),
    path(
        "add-to-black-list/",
        AddToBlackListView.as_view(),
        name="add_to_black_list",
    ),
    path(
        "delete-from-blacklist/",
        DeleteFromBlacklistView.as_view(),
        name="delete_from_blacklist",
    ),
    path(
        "clear-blacklist-list/",
        ClearBlackList.as_view(),
        name="clear_blacklist_list",
    ),
    path("hide-company/", HideCompanyView.as_view(), name="hide_company"),
    path(
        "delete-from-hidden-companies/",
        DeleteFromHiddenCompaniesView.as_view(),
        name="delete_from_hidden_companies",
    ),
    path(
        "clear-hidden-companies-list/",
        ClearHiddenCompaniesList.as_view(),
        name="clear_hidden_companies_list",
    ),
]

job_parser/profiles/urls.py
from django.urls import path
from profiles import views

app_name = "profiles"

urlpatterns = [
    path("profile/<str:username>/", views.ProfileView.as_view(), name="profile"),
]

job_parser/templates/base.html
{% load static %}
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Vacancium {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/d8c390d801.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto+Mono:ital,wght@0,100;0,400;0,500;0,600;0,700;1,100;1,400;1,500;1,600;1,700&family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    
  </head>
  <body>
    <header class="header">
      <nav class="navbar navbar-expand-lg">
          <div class="container">
              <a class="navbar-brand text-light" href="{% url 'home' %}"><img class="logo" src="{% static 'images/wolf.svg' %}" alt="wolf" width="40"></a>
              <div class="brand-text-wrap">
                <a href="{% url 'home' %}" class="navbar-brand-text">В лес не убежит.</a>
              </div>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                  aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                  <ul class="navbar-nav ms-auto">
                      {% if user.is_authenticated %}
                          <li class="nav-item">
                              <a class="nav-link text-light" href="{% url 'account_logout' %}">Выйти</a>
                          </li>
                          <li class="nav-item">
                              <a class="nav-link text-light" href="{% url 'profiles:profile' request.user.username %}">Профиль</a>
                          </li>
                      {% else %}
                          <li class="nav-item">
                              <a class="nav-link text-light" href="{% url 'account_login' %}">Войти</a>
                          </li>
                          <li class="nav-item">
                              <a class="nav-link text-light" href="{% url 'account_signup' %}">Регистрация</a>
                          </li>
                      {% endif %}
                  </ul>
              </div>
          </div>
      </nav>
  </header>
    
    <div class="container my-5 content">{% block content %} {% endblock %}</div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>  </body>
</html>